/**
 * @file embedded_web.h
 * @brief 内嵌网页内容
 */

#ifndef EMBEDDED_WEB_H
#define EMBEDDED_WEB_H

// 内嵌的 HTML 页面
static const char* embedded_index_html = 
"<!DOCTYPE html>\n"
"<html lang=\"zh-CN\">\n"
"<head>\n"
"    <meta charset=\"UTF-8\">\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"    <title>LD Radar Monitor</title>\n"
"    <style>\n"
"        * { margin: 0; padding: 0; box-sizing: border-box; }\n"
"        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #1a1a2e; color: #eee; min-height: 100vh; }\n"
"        .container { max-width: 1200px; margin: 0 auto; padding: 20px; }\n"
"        header { background: #16213e; padding: 15px 20px; border-radius: 10px; margin-bottom: 20px; display: flex; justify-content: space-between; align-items: center; }\n"
"        h1 { font-size: 24px; color: #00d4ff; }\n"
"        .status { display: flex; gap: 20px; align-items: center; }\n"
"        .status-item { display: flex; align-items: center; gap: 8px; }\n"
"        .status-dot { width: 10px; height: 10px; border-radius: 50%; background: #4CAF50; animation: pulse 2s infinite; }\n"
"        .status-dot.disconnected { background: #f44336; animation: none; }\n"
"        @keyframes pulse { 0%, 100% { opacity: 1; } 50% { opacity: 0.5; } }\n"
"        .main-content { display: grid; grid-template-columns: 1fr 300px; gap: 20px; }\n"
"        .canvas-container { background: #16213e; border-radius: 10px; padding: 20px; position: relative; }\n"
"        #radarCanvas { width: 100%; height: 500px; background: #0f0f23; border-radius: 8px; }\n"
"        .sidebar { display: flex; flex-direction: column; gap: 15px; }\n"
"        .card { background: #16213e; border-radius: 10px; padding: 15px; }\n"
"        .card h3 { font-size: 14px; color: #888; margin-bottom: 10px; text-transform: uppercase; }\n"
"        .target-list { max-height: 300px; overflow-y: auto; }\n"
"        .target-item { background: #1a1a2e; padding: 10px; border-radius: 5px; margin-bottom: 8px; }\n"
"        .target-item h4 { color: #00d4ff; margin-bottom: 5px; }\n"
"        .target-item p { font-size: 12px; color: #888; }\n"
"        .info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; }\n"
"        .info-item { background: #1a1a2e; padding: 10px; border-radius: 5px; text-align: center; }\n"
"        .info-item .value { font-size: 20px; color: #00d4ff; font-weight: bold; }\n"
"        .info-item .label { font-size: 11px; color: #888; }\n"
"        .btn { background: #00d4ff; color: #1a1a2e; border: none; padding: 10px 20px; border-radius: 5px; cursor: pointer; font-weight: bold; transition: all 0.3s; }\n"
"        .btn:hover { background: #00a8cc; }\n"
"        .btn.secondary { background: #333; color: #fff; }\n"
"        .settings-group { margin-bottom: 15px; }\n"
"        .settings-group label { display: block; font-size: 12px; color: #888; margin-bottom: 5px; }\n"
"        .settings-group input, .settings-group select { width: 100%; padding: 8px; background: #1a1a2e; border: 1px solid #333; border-radius: 5px; color: #fff; }\n"
"        .log-container { background: #0f0f23; border-radius: 5px; padding: 10px; max-height: 200px; overflow-y: auto; font-family: monospace; font-size: 11px; }\n"
"        .log-entry { margin-bottom: 3px; }\n"
"        .log-entry.info { color: #4CAF50; }\n"
"        .log-entry.warn { color: #ff9800; }\n"
"        .log-entry.error { color: #f44336; }\n"
"    </style>\n"
"</head>\n"
"<body>\n"
"    <div class=\"container\">\n"
"        <header>\n"
"            <h1>📡 LD Radar Monitor</h1>\n"
"            <div class=\"status\">\n"
"                <div class=\"status-item\">\n"
"                    <div class=\"status-dot\" id=\"wsStatus\"></div>\n"
"                    <span id=\"wsStatusText\">Connecting...</span>\n"
"                </div>\n"
"                <div class=\"status-item\">\n"
"                    <span>Targets: <strong id=\"targetCount\">0</strong></span>\n"
"                </div>\n"
"            </div>\n"
"        </header>\n"
"        \n"
"        <div class=\"main-content\">\n"
"            <div class=\"canvas-container\">\n"
"                <canvas id=\"radarCanvas\"></canvas>\n"
"            </div>\n"
"            \n"
"            <div class=\"sidebar\">\n"
"                <div class=\"card\">\n"
"                    <h3>System Info</h3>\n"
"                    <div class=\"info-grid\">\n"
"                        <div class=\"info-item\">\n"
"                            <div class=\"value\" id=\"freeHeap\">--</div>\n"
"                            <div class=\"label\">Free Heap (KB)</div>\n"
"                        </div>\n"
"                        <div class=\"info-item\">\n"
"                            <div class=\"value\" id=\"fps\">--</div>\n"
"                            <div class=\"label\">FPS</div>\n"
"                        </div>\n"
"                        <div class=\"info-item\">\n"
"                            <div class=\"value\" id=\"uptime\">--</div>\n"
"                            <div class=\"label\">Uptime (s)</div>\n"
"                        </div>\n"
"                        <div class=\"info-item\">\n"
"                            <div class=\"value\" id=\"wsClients\">0</div>\n"
"                            <div class=\"label\">WS Clients</div>\n"
"                        </div>\n"
"                    </div>\n"
"                </div>\n"
"                \n"
"                <div class=\"card\">\n"
"                    <h3>Targets</h3>\n"
"                    <div class=\"target-list\" id=\"targetList\">\n"
"                        <p style=\"color: #888; text-align: center; padding: 20px;\">No targets detected</p>\n"
"                    </div>\n"
"                </div>\n"
"                \n"
"                <div class=\"card\">\n"
"                    <h3>Settings</h3>\n"
"                    <div class=\"settings-group\">\n"
"                        <label>Mount Mode</label>\n"
"                        <select id=\"mountMode\">\n"
"                            <option value=\"ceiling\">Ceiling (Top)</option>\n"
"                            <option value=\"side\" selected>Side (Wall)</option>\n"
"                        </select>\n"
"                    </div>\n"
"                    <div class=\"settings-group\">\n"
                        <label>Room Width (m)</label>\n"
"                        <input type=\"number\" id=\"roomWidth\" value=\"6\" step=\"0.5\" min=\"1\" max=\"20\">\n"
"                    </div>\n"
"                    <div class=\"settings-group\">\n"
"                        <label>Room Depth (m)</label>\n"
"                        <input type=\"number\" id=\"roomDepth\" value=\"8\" step=\"0.5\" min=\"1\" max=\"20\">\n"
"                    </div>\n"
"                    <button class=\"btn\" onclick=\"saveSettings()\">Save Settings</button>\n"
"                </div>\n"
"                \n"
"                <div class=\"card\">\n"
"                    <h3>Log</h3>\n"
"                    <div class=\"log-container\" id=\"logContainer\"></div>\n"
"                </div>\n"
"            </div>\n"
"        </div>\n"
"    </div>\n"
"\n"
"    <script>\n"
"        // Canvas setup\n"
"        const canvas = document.getElementById('radarCanvas');\n"
"        const ctx = canvas.getContext('2d');\n"
"        let ws = null;\n"
"        let targets = [];\n"
"        let trails = {};\n"
"        let frameCount = 0;\n"
"        let lastFpsTime = Date.now();\n"
"        let fps = 0;\n"
"        \n"
"        // Settings\n"
"        let settings = {\n"
"            mountMode: 'side',\n"
"            roomWidth: 6,\n"
"            roomDepth: 8,\n"
"            trailLength: 60\n"
"        };\n"
"        \n"
"        // Resize canvas\n"
"        function resizeCanvas() {\n"
"            const rect = canvas.parentElement.getBoundingClientRect();\n"
"            canvas.width = rect.width - 40;\n"
"            canvas.height = 500;\n"
"        }\n"
"        window.addEventListener('resize', resizeCanvas);\n"
"        resizeCanvas();\n"
"        \n"
"        // Log function\n"
"        function log(msg, type = 'info') {\n"
"            const container = document.getElementById('logContainer');\n"
"            const entry = document.createElement('div');\n"
"            entry.className = 'log-entry ' + type;\n"
"            entry.textContent = '[' + new Date().toLocaleTimeString() + '] ' + msg;\n"
"            container.appendChild(entry);\n"
"            container.scrollTop = container.scrollHeight;\n"
"            if (container.children.length > 50) container.removeChild(container.firstChild);\n"
"        }\n"
"        \n"
"        // WebSocket connection\n"
"        function connectWebSocket() {\n"
"            const wsUrl = 'ws://' + window.location.host + '/ws';\n"
"            log('Connecting to ' + wsUrl);\n"
"            ws = new WebSocket(wsUrl);\n"
"            \n"
"            ws.onopen = function() {\n"
"                log('WebSocket connected', 'info');\n"
"                document.getElementById('wsStatus').classList.remove('disconnected');\n"
"                document.getElementById('wsStatusText').textContent = 'Connected';\n"
"                ws.send(JSON.stringify({type: 'subscribe'}));\n"
"            };\n"
"            \n"
"            ws.onmessage = function(e) {\n"
"                try {\n"
"                    const data = JSON.parse(e.data);\n"
"                    if (data.type === 'radar_data') {\n"
"                        handleRadarData(data);\n"
"                    }\n"
"                } catch(err) {}\n"
"            };\n"
"            \n"
"            ws.onclose = function() {\n"
"                log('WebSocket disconnected', 'warn');\n"
"                document.getElementById('wsStatus').classList.add('disconnected');\n"
"                document.getElementById('wsStatusText').textContent = 'Disconnected';\n"
"                setTimeout(connectWebSocket, 3000);\n"
"            };\n"
"            \n"
"            ws.onerror = function(err) {\n"
"                log('WebSocket error', 'error');\n"
"            };\n"
"        }\n"
"        \n"
"        // Handle radar data\n"
"        function handleRadarData(data) {\n"
"            targets = data.targets || [];\n"
"            document.getElementById('targetCount').textContent = targets.length;\n"
"            \n"
"            // Update trails\n"
"            targets.forEach(function(t) {\n"
"                if (!trails[t.id]) trails[t.id] = [];\n"
"                trails[t.id].push({x: t.x, y: t.y});\n"
"                if (trails[t.id].length > settings.trailLength) trails[t.id].shift();\n"
"            });\n"
"            \n"
"            // Update FPS\n"
"            frameCount++;\n"
"            const now = Date.now();\n"
"            if (now - lastFpsTime >= 1000) {\n"
"                fps = frameCount;\n"
"                frameCount = 0;\n"
"                lastFpsTime = now;\n"
"                document.getElementById('fps').textContent = fps;\n"
"            }\n"
"            \n"
"            // Update target list\n"
"            updateTargetList();\n"
"        }\n"
"        \n"
"        // Update target list UI\n"
"        function updateTargetList() {\n"
"            const container = document.getElementById('targetList');\n"
"            if (targets.length === 0) {\n"
"                container.innerHTML = '<p style=\"color: #888; text-align: center; padding: 20px;\">No targets detected</p>';\n"
"                return;\n"
"            }\n"
"            container.innerHTML = targets.map(function(t) {\n"
"                return '<div class=\"target-item\"><h4>Target #' + t.id + '</h4><p>X: ' + t.x.toFixed(2) + 'm Y: ' + t.y.toFixed(2) + 'm Z: ' + t.z.toFixed(2) + 'm</p></div>';\n"
"            }).join('');\n"
"        }\n"
"        \n"
"        // Draw radar canvas\n"
"        function draw() {\n"
"            const w = canvas.width;\n"
"            const h = canvas.height;\n"
"            const cx = w / 2;\n"
"            const cy = h - 50;\n"
"            const scale = Math.min(w, h) / (settings.roomDepth * 2);\n"
"            \n"
"            // Clear\n"
"            ctx.fillStyle = '#0f0f23';\n"
"            ctx.fillRect(0, 0, w, h);\n"
"            \n"
"            // Draw grid\n"
"            ctx.strokeStyle = '#1a3a5c';\n"
"            ctx.lineWidth = 1;\n"
"            for (let i = 0; i <= settings.roomDepth; i++) {\n"
"                const y = cy - i * scale;\n"
"                ctx.beginPath(); ctx.moveTo(0, y); ctx.lineTo(w, y); ctx.stroke();\n"
"                ctx.fillStyle = '#3a5a7c'; ctx.font = '10px sans-serif'; ctx.fillText(i + 'm', 5, y - 5);\n"
"            }\n"
"            for (let i = -Math.floor(settings.roomWidth/2); i <= Math.floor(settings.roomWidth/2); i++) {\n"
"                const x = cx + i * scale;\n"
"                ctx.beginPath(); ctx.moveTo(x, 0); ctx.lineTo(x, cy); ctx.stroke();\n"
"            }\n"
"            \n"
"            // Draw radar position\n"
"            ctx.fillStyle = '#00d4ff';\n"
"            ctx.beginPath(); ctx.arc(cx, cy, 10, 0, Math.PI * 2); ctx.fill();\n"
"            ctx.fillStyle = '#fff'; ctx.font = '12px sans-serif'; ctx.textAlign = 'center'; ctx.fillText('RADAR', cx, cy + 25);\n"
"            \n"
"            // Draw trails\n"
"            Object.keys(trails).forEach(function(id) {\n"
"                const trail = trails[id];\n"
"                if (trail.length < 2) return;\n"
"                ctx.strokeStyle = 'rgba(0, 212, 255, 0.3)';\n"
"                ctx.lineWidth = 2;\n"
"                ctx.beginPath();\n"
"                trail.forEach(function(p, i) {\n"
"                    const x = cx + p.x * scale;\n"
"                    const y = cy - p.y * scale;\n"
"                    if (i === 0) ctx.moveTo(x, y); else ctx.lineTo(x, y);\n"
"                });\n"
"                ctx.stroke();\n"
"            });\n"
"            \n"
"            // Draw targets\n"
"            targets.forEach(function(t) {\n"
"                const x = cx + t.x * scale;\n"
"                const y = cy - t.y * scale;\n"
"                ctx.fillStyle = '#ff6b6b';\n"
"                ctx.beginPath(); ctx.arc(x, y, 8, 0, Math.PI * 2); ctx.fill();\n"
"                ctx.fillStyle = '#fff'; ctx.font = '10px sans-serif'; ctx.textAlign = 'center'; ctx.fillText('#' + t.id, x, y - 12);\n"
"            });\n"
"            \n"
"            requestAnimationFrame(draw);\n"
"        }\n"
"        \n"
"        // Fetch system info\n"
"        function fetchSystemInfo() {\n"
"            fetch('/api/status').then(function(r) { return r.json(); }).then(function(data) {\n"
"                document.getElementById('wsClients').textContent = data.websocket_clients || 0;\n"
"            }).catch(function() {});\n"
"            fetch('/api/system/info').then(function(r) { return r.json(); }).then(function(data) {\n"
"                document.getElementById('freeHeap').textContent = Math.round(data.free_heap / 1024);\n"
"                document.getElementById('uptime').textContent = Math.round(data.uptime);\n"
"            }).catch(function() {});\n"
"        }\n"
"        \n"
"        // Save settings\n"
"        function saveSettings() {\n"
"            settings.mountMode = document.getElementById('mountMode').value;\n"
"            settings.roomWidth = parseFloat(document.getElementById('roomWidth').value);\n"
"            settings.roomDepth = parseFloat(document.getElementById('roomDepth').value);\n"
"            log('Settings saved');\n"
"        }\n"
"        \n"
"        // Initialize\n"
"        connectWebSocket();\n"
"        draw();\n"
"        setInterval(fetchSystemInfo, 5000);\n"
"        fetchSystemInfo();\n"
"        log('System initialized');\n"
"    </script>\n"
"</body>\n"
"</html>\n";

#endif // EMBEDDED_WEB_H
