/**
 * @file upload_page.h
 * @brief 内嵌的文件上传管理页面
 */

#ifndef UPLOAD_PAGE_H
#define UPLOAD_PAGE_H

static const char* upload_page_html =
"<!DOCTYPE html>\n"
"<html lang=\"zh-CN\">\n"
"<head>\n"
"    <meta charset=\"UTF-8\">\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"    <title>LD Radar - File Manager</title>\n"
"    <style>\n"
"        * { margin: 0; padding: 0; box-sizing: border-box; }\n"
"        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #1a1a2e; color: #eee; min-height: 100vh; padding: 20px; }\n"
"        .container { max-width: 1000px; margin: 0 auto; }\n"
"        h1 { color: #00d4ff; margin-bottom: 20px; font-size: 24px; }\n"
"        .card { background: #16213e; border-radius: 10px; padding: 20px; margin-bottom: 20px; }\n"
"        .card h2 { font-size: 16px; color: #888; margin-bottom: 15px; text-transform: uppercase; }\n"
"        .info-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 15px; margin-bottom: 20px; }\n"
"        .info-item { background: #1a1a2e; padding: 15px; border-radius: 8px; text-align: center; }\n"
"        .info-item .value { font-size: 24px; color: #00d4ff; font-weight: bold; }\n"
"        .info-item .label { font-size: 12px; color: #888; margin-top: 5px; }\n"
"        .upload-area { border: 2px dashed #3a5a7c; border-radius: 10px; padding: 40px; text-align: center; margin-bottom: 20px; transition: all 0.3s; }\n"
"        .upload-area.dragover { border-color: #00d4ff; background: rgba(0, 212, 255, 0.1); }\n"
"        .upload-area input[type=\"file\"] { display: none; }\n"
"        .upload-area label { cursor: pointer; display: block; }\n"
"        .upload-area .icon { font-size: 48px; margin-bottom: 10px; }\n"
"        .upload-area p { color: #888; }\n"
"        .btn { background: #00d4ff; color: #1a1a2e; border: none; padding: 10px 20px; border-radius: 5px; cursor: pointer; font-weight: bold; transition: all 0.3s; margin: 5px; }\n"
"        .btn:hover { background: #00a8cc; }\n"
"        .btn.danger { background: #f44336; color: #fff; }\n"
"        .btn.danger:hover { background: #d32f2f; }\n"
"        .btn.small { padding: 5px 10px; font-size: 12px; }\n"
"        table { width: 100%; border-collapse: collapse; }\n"
"        th, td { padding: 12px; text-align: left; border-bottom: 1px solid #2a3a5c; }\n"
"        th { color: #888; font-weight: normal; text-transform: uppercase; font-size: 12px; }\n"
"        .file-icon { margin-right: 8px; }\n"
"        .file-name { color: #fff; }\n"
"        .file-size { color: #888; }\n"
"        .actions { white-space: nowrap; }\n"
"        .path-bar { background: #0f0f23; padding: 10px 15px; border-radius: 5px; margin-bottom: 15px; font-family: monospace; }\n"
"        .path-bar span { color: #00d4ff; }\n"
"        .status { padding: 10px 15px; border-radius: 5px; margin-bottom: 15px; display: none; }\n"
"        .status.success { background: rgba(76, 175, 80, 0.2); color: #4CAF50; display: block; }\n"
"        .status.error { background: rgba(244, 67, 54, 0.2); color: #f44336; display: block; }\n"
"        .progress { width: 100%; height: 4px; background: #1a1a2e; border-radius: 2px; margin-top: 10px; display: none; }\n"
"        .progress-bar { height: 100%; background: #00d4ff; border-radius: 2px; width: 0%; transition: width 0.3s; }\n"
"        .empty-state { text-align: center; padding: 40px; color: #888; }\n"
"        .nav { display: flex; justify-content: space-between; align-items: center; margin-bottom: 20px; }\n"
"        .nav a { color: #00d4ff; text-decoration: none; }\n"
"        .nav a:hover { text-decoration: underline; }\n"
"    </style>\n"
"</head>\n"
"<body>\n"
"    <div class=\"container\">\n"
"        <div class=\"nav\">\n"
"            <h1>📁 File Manager</h1>\n"
"            <a href=\"/\">→ Open Radar App</a>\n"
"        </div>\n"
"        <div class=\"status\" id=\"status\"></div>\n"
"        <div class=\"card\">\n"
"            <h2>Storage Info</h2>\n"
"            <div class=\"info-grid\">\n"
"                <div class=\"info-item\">\n"
"                    <div class=\"value\" id=\"totalSize\">--</div>\n"
"                    <div class=\"label\">Total (KB)</div>\n"
"                </div>\n"
"                <div class=\"info-item\">\n"
"                    <div class=\"value\" id=\"usedSize\">--</div>\n"
"                    <div class=\"label\">Used (KB)</div>\n"
"                </div>\n"
"                <div class=\"info-item\">\n"
"                    <div class=\"value\" id=\"freeSize\">--</div>\n"
"                    <div class=\"label\">Free (KB)</div>\n"
"                </div>\n"
"                <div class=\"info-item\">\n"
"                    <div class=\"value\" id=\"fileCount\">--</div>\n"
"                    <div class=\"label\">Files</div>\n"
"                </div>\n"
"            </div>\n"
"        </div>\n"
"        <div class=\"card\">\n"
"            <h2>Upload Files</h2>\n"
"            <div class=\"upload-area\" id=\"dropZone\">\n"
"                <label for=\"fileInput\">\n"
"                    <div class=\"icon\">📤</div>\n"
"                    <p>Drag and drop files here, or click to select</p>\n"
"                    <p style=\"font-size: 12px; margin-top: 10px;\">Files will be uploaded to /www/ directory</p>\n"
"                </label>\n"
"                <input type=\"file\" id=\"fileInput\" multiple>\n"
"            </div>\n"
"            <div class=\"progress\" id=\"progress\">\n"
"                <div class=\"progress-bar\" id=\"progressBar\"></div>\n"
"            </div>\n"
"        </div>\n"
"        <div class=\"card\">\n"
"            <h2>Files in /www/</h2>\n"
"            <div class=\"path-bar\">Path: <span>/storage/www/</span></div>\n"
"            <table>\n"
"                <thead>\n"
"                    <tr>\n"
"                        <th>Name</th>\n"
"                        <th>Size</th>\n"
"                        <th>Actions</th>\n"
"                    </tr>\n"
"                </thead>\n"
"                <tbody id=\"fileList\">\n"
"                    <tr><td colspan=\"3\" class=\"empty-state\">Loading...</td></tr>\n"
"                </tbody>\n"
"            </table>\n"
"        </div>\n"
"        <div class=\"card\">\n"
"            <h2>Danger Zone</h2>\n"
"            <p style=\"color: #888; margin-bottom: 15px;\">Format will erase all files in storage partition.</p>\n"
"            <button class=\"btn danger\" onclick=\"formatStorage()\">Format Storage</button>\n"
"        </div>\n"
"    </div>\n"
"    <script>\n"
"        function showStatus(msg, isError) {\n"
"            var el = document.getElementById('status');\n"
"            el.textContent = msg;\n"
"            el.className = 'status ' + (isError ? 'error' : 'success');\n"
"            setTimeout(function() { el.style.display = 'none'; }, 5000);\n"
"        }\n"
"        function formatSize(bytes) {\n"
"            if (bytes < 1024) return bytes + ' B';\n"
"            if (bytes < 1024 * 1024) return (bytes / 1024).toFixed(1) + ' KB';\n"
"            return (bytes / 1024 / 1024).toFixed(2) + ' MB';\n"
"        }\n"
"        function loadFsInfo() {\n"
"            fetch('/api/fs/info').then(function(r) { return r.json(); }).then(function(data) {\n"
"                document.getElementById('totalSize').textContent = Math.round(data.total_bytes / 1024);\n"
"                document.getElementById('usedSize').textContent = Math.round(data.used_bytes / 1024);\n"
"                document.getElementById('freeSize').textContent = Math.round(data.free_bytes / 1024);\n"
"                document.getElementById('fileCount').textContent = data.file_count;\n"
"            }).catch(function(e) { console.error(e); });\n"
"        }\n"
"        function loadFileList() {\n"
"            fetch('/api/files/list?path=/storage/www').then(function(r) { return r.json(); }).then(function(data) {\n"
"                var tbody = document.getElementById('fileList');\n"
"                if (!data.files || data.files.length === 0) {\n"
"                    tbody.innerHTML = '<tr><td colspan=\"3\" class=\"empty-state\">No files uploaded. Upload files to see them here.</td></tr>';\n"
"                    return;\n"
"                }\n"
"                tbody.innerHTML = data.files.map(function(f) {\n"
"                    var icon = f.is_dir ? '📁' : '📄';\n"
"                    var name = f.name;\n"
"                    if (!f.is_dir && (name.endsWith('.html') || name.endsWith('.htm'))) icon = '🌐';\n"
"                    if (!f.is_dir && name.endsWith('.css')) icon = '🎨';\n"
"                    if (!f.is_dir && name.endsWith('.js')) icon = '⚡';\n"
"                    var actions = '<button class=\"btn small danger\" onclick=\"deleteFile(\\'' + f.name + '\\')\">Delete</button>';\n"
"                    if (!f.is_dir && (name.endsWith('.html') || name.endsWith('.htm'))) {\n"
"                        actions = '<a class=\"btn small\" href=\"/view/' + name + '\" target=\"_blank\">View</a> ' + actions;\n"
"                    }\n"
"                    return '<tr><td><span class=\"file-icon\">' + icon + '</span><span class=\"file-name\">' + f.name + '</span></td><td class=\"file-size\">' + formatSize(f.size) + '</td><td class=\"actions\">' + actions + '</td></tr>';\n"
"                }).join('');\n"
"            }).catch(function(e) {\n"
"                document.getElementById('fileList').innerHTML = '<tr><td colspan=\"3\" class=\"empty-state\">Failed to load file list</td></tr>';\n"
"            });\n"
"        }\n"
"        var mqttPaused = false;\n"
"        function pauseMqtt(cb) {\n"
"            fetch('/api/mqtt/pause', {method:'POST'}).then(function(){mqttPaused=true;if(cb)cb();});\n"
"        }\n"
"        function resumeMqtt(cb) {\n"
"            fetch('/api/mqtt/resume', {method:'POST'}).then(function(){mqttPaused=false;if(cb)cb();});\n"
"        }\n"
"        function uploadFile(file, onDone) {\n"
"            var xhr = new XMLHttpRequest();\n"
"            var path = '/storage/www/' + file.name;\n"
"            var reader = new FileReader();\n"
"            reader.onload = function(e) {\n"
"                xhr.open('POST', '/api/files/upload?path=' + encodeURIComponent(path), true);\n"
"                xhr.setRequestHeader('Content-Type', 'application/octet-stream');\n"
"                xhr.upload.onprogress = function(ev) {\n"
"                    if (ev.lengthComputable) {\n"
"                        var loaded = formatSize(ev.loaded);\n"
"                        var total = formatSize(ev.total);\n"
"                        showStatus('Uploading: ' + loaded + ' / ' + total, false);\n"
"                    }\n"
"                };\n"
"                xhr.onload = function() {\n"
"                    if (xhr.status === 200) {\n"
"                        try {\n"
"                            var data = JSON.parse(xhr.responseText);\n"
"                            if (data.success) {\n"
"                                showStatus('Uploaded: ' + file.name, false);\n"
"                            } else {\n"
"                                showStatus('Upload failed: ' + (data.message || 'Unknown error'), true);\n"
"                            }\n"
"                        } catch(ex) {\n"
"                            showStatus('Uploaded: ' + file.name, false);\n"
"                        }\n"
"                    } else {\n"
"                        showStatus('Upload failed: HTTP ' + xhr.status, true);\n"
"                    }\n"
"                    loadFileList();\n"
"                    loadFsInfo();\n"
"                    if (onDone) onDone();\n"
"                };\n"
"                xhr.onerror = function() {\n"
"                    showStatus('Upload failed: network error', true);\n"
"                    if (onDone) onDone();\n"
"                };\n"
"                xhr.send(e.target.result);\n"
"            };\n"
"            reader.readAsArrayBuffer(file);\n"
"        }\n"
"        function uploadFiles(files) {\n"
"            var i = 0;\n"
"            function next() {\n"
"                if (i >= files.length) {\n"
"                    resumeMqtt(function(){showStatus('All uploads complete', false);});\n"
"                    return;\n"
"                }\n"
"                uploadFile(files[i++], next);\n"
"            }\n"
"            pauseMqtt(next);\n"
"        }\n"
"        function deleteFile(name) {\n"
"            if (!confirm('Delete ' + name + '?')) return;\n"
"            fetch('/api/files/delete?path=/storage/www/' + encodeURIComponent(name), { method: 'DELETE' })\n"
"                .then(function(r) { return r.json(); })\n"
"                .then(function(data) {\n"
"                    if (data.success) {\n"
"                        showStatus('Deleted: ' + name, false);\n"
"                        loadFileList();\n"
"                        loadFsInfo();\n"
"                    } else {\n"
"                        showStatus('Delete failed', true);\n"
"                    }\n"
"                });\n"
"        }\n"
"        function formatStorage() {\n"
"            if (!confirm('This will erase ALL files! Are you sure?')) return;\n"
"            if (!confirm('Really? This cannot be undone!')) return;\n"
"            fetch('/api/fs/format', { method: 'POST' })\n"
"                .then(function(r) { return r.json(); })\n"
"                .then(function(data) {\n"
"                    showStatus(data.success ? 'Storage formatted' : 'Format failed', !data.success);\n"
"                    loadFileList();\n"
"                    loadFsInfo();\n"
"                });\n"
"        }\n"
"        // Drag and drop\n"
"        var dropZone = document.getElementById('dropZone');\n"
"        var fileInput = document.getElementById('fileInput');\n"
"        dropZone.addEventListener('dragover', function(e) { e.preventDefault(); dropZone.classList.add('dragover'); });\n"
"        dropZone.addEventListener('dragleave', function() { dropZone.classList.remove('dragover'); });\n"
"        dropZone.addEventListener('drop', function(e) {\n"
"            e.preventDefault();\n"
"            dropZone.classList.remove('dragover');\n"
"            uploadFiles(e.dataTransfer.files);\n"
"        });\n"
"        fileInput.addEventListener('change', function(e) {\n"
"            uploadFiles(e.target.files);\n"
"        });\n"
"        // Initial load\n"
"        loadFsInfo();\n"
"        loadFileList();\n"
"    </script>\n"
"</body>\n"
"</html>\n";

#endif // UPLOAD_PAGE_H
